# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'appscheduler' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appscheduler

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'appschedulerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'appscheduler-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appscheduler-tvOS

  target 'appscheduler-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Required by RNFirebase
pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Auth', '~> 5.15.0'
pod 'Firebase/Database', '~> 5.15.0'